// flow-typed signature: e8ecb3e4d92a52d616a463c23248e1d9
// flow-typed version: <<STUB>>/apollo-boost_v0.1.6/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-boost'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-boost' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-boost/lib/index' {
  declare module.exports: any
}

// Filename aliases
declare module 'apollo-boost/lib/index.js' {
  declare module.exports: $Exports<'apollo-boost/lib/index'>
}
