// flow-typed signature: 7b487514d48c9571668d42fdb34e2e40
// flow-typed version: <<STUB>>/next-compose-plugins_v2.1.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-compose-plugins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-compose-plugins' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-compose-plugins/lib/compose' {
  declare module.exports: any
}

declare module 'next-compose-plugins/lib/index' {
  declare module.exports: any
}

declare module 'next-compose-plugins/lib/optional' {
  declare module.exports: any
}

declare module 'next-compose-plugins/lib/phases' {
  declare module.exports: any
}

// Filename aliases
declare module 'next-compose-plugins/lib/compose.js' {
  declare module.exports: $Exports<'next-compose-plugins/lib/compose'>
}
declare module 'next-compose-plugins/lib/index.js' {
  declare module.exports: $Exports<'next-compose-plugins/lib/index'>
}
declare module 'next-compose-plugins/lib/optional.js' {
  declare module.exports: $Exports<'next-compose-plugins/lib/optional'>
}
declare module 'next-compose-plugins/lib/phases.js' {
  declare module.exports: $Exports<'next-compose-plugins/lib/phases'>
}
