// flow-typed signature: 1823c8587e57090fab65cacb93d3f51c
// flow-typed version: <<STUB>>/spritesh_v1.2.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spritesh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spritesh' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spritesh/bin/spritesh' {
  declare module.exports: any
}

// Filename aliases
declare module 'spritesh/bin/spritesh.js' {
  declare module.exports: $Exports<'spritesh/bin/spritesh'>
}
