// flow-typed signature: fd433f218f048939b762d5e2474f45d9
// flow-typed version: <<STUB>>/@zeit/next-css_v0.2.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@zeit/next-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@zeit/next-css' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@zeit/next-css/commons-chunk-config' {
  declare module.exports: any
}

declare module '@zeit/next-css/css-loader-config' {
  declare module.exports: any
}

// Filename aliases
declare module '@zeit/next-css/commons-chunk-config.js' {
  declare module.exports: $Exports<'@zeit/next-css/commons-chunk-config'>
}
declare module '@zeit/next-css/css-loader-config.js' {
  declare module.exports: $Exports<'@zeit/next-css/css-loader-config'>
}
declare module '@zeit/next-css/index' {
  declare module.exports: $Exports<'@zeit/next-css'>
}
declare module '@zeit/next-css/index.js' {
  declare module.exports: $Exports<'@zeit/next-css'>
}
